# Generated by Django 4.2.11 on 2024-03-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs'),
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_pictures'),
        ),
    ]
